#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "${3}/tmp/App/ShowHiddenFiles.zip" -d "${3}/tmp/App/"
cp -Rf "${3}/tmp/App/ShowHiddenFiles.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/ShowHiddenFiles.app"
