#!/bin/bash
logfil="/Library/Logs/SCT/sct_install_`date +%Y%m%d`.log"

echo "--------------- KextUtility Installation Start -------------" >> $logfil
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	echo "$(date +%T): tools dir didn't exist, created one" >> $logfil
	chown "$USER" "$HOME/Desktop/Tools"
	echo "$(date +%T): owner set to $USER" >> $logfil
fi
unzip "${3}/tmp/App/KextUtility.zip" -d "${3}/tmp/App/"
echo "$(date +%T): unzipped KextUtility, now copying it to tools" >> $logfil
cp -Rf "${3}/tmp/App/KextUtility-7-8-10.app" "$HOME/Desktop/Tools/"
cp -Rf "${3}/tmp/App/KextUtility-9.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/KextUtility-7-8-10.app"
chown -R "$USER" "$HOME/Desktop/Tools/KextUtility-9.app"

echo "---------------- KextUtility Installation End --------------" >> $logfil
echo "" >> $logfil	